### ISSUE TITLE
Node.UCI and Anticrux Javascript Chess UCI

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#10]
Hello ecrucru,

Do you have any idea how to run Anticrux JS  with **Node.UCI** https://github.com/ebemunk/node-uci ?

cf. my thread http://talkchess.com/forum/viewtopic.php?t=65149&highlight=node

**Comment by ecrucru** [comment]
Hello @yellow-panther,

AntiCrux is a library written in JavaScript. It natively runs on web-browsers and NodeJS, so you don't need a wrapper to communicate with it via UCI :
https://github.com/ecrucru/anticrux/blob/master/anticrux-demo.js

Node-UCI is useful when you want to pilot an UCI-compatible engine generically, whatever it embeds a dedicated API or is written in JavaScript.

You still may call AntiCrux via UCI if you execute `node.exe --expose-gc anticrux-engine.js`. But I have not checked if node-uci supports the command line parameters. In any case, please refer to the README of the other project to know how to call the engine. At least, you should edit `new Engine("the_command_above")` and then you run `node your_new_script.js`.

Regards

**Comment by ecrucru** [comment]
Hello @yellow-panther,

After investigation, node-uci should be enhanced to support the argument line in `spawn`. Also for 2 OS and 2 engines, I can't get any output in the console : this is weird despite the provided example.

You should contact the developer to know more about his project.

Regards.

**Comment by ebemunk** [comment]
Hi, I'm the maintainer of node-uci. I just came upon this issue (years later) and wanted to know if you remember which engines you tried it with? Also I will make a note to add `spawn` arguments in my lib to be able to support AntiCrux.
Thanks!

**Comment by ecrucru** [comment]
Hello @ebemunk,

I certainly used Gull and TomiTank for the test on Windows, then Toga and self-compiled Stockfish on Linux.

Thanks if you can improve your usage of spawn : this will support all JS/Python/... engines.

Regards
