### ISSUE TITLE
Nakshatra CECP/WB Suicide Chess for Windows?

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#11]
Hello ecrucru,

**Nakshatra** https://github.com/goutham/nakshatra supports **CECP/XB-protocol** and was primarily designed for Linux. If you are able to build a Windows binary (32-64 bit) please let me know.
The author is obviously using only Linux.

**Comment by ecrucru** [comment]
Hello,

This is a service that I can't deliver to you. If the developer has chosen to not compile his application for some platforms, it is unfortunately his right to do so. No app, no user, that's all...

Also, please remind that this issue tracker is solely dedicated to support AntiCrux. Please ask questions related to it **only**.

Regards.
