### ISSUE TITLE
Online opening book and egtb support

### ISSUE THREAD

**Issue by gbtami** [ecrucru/anticrux#13]
It would be nice to ad add support for https://github.com/niklasf/lila-openingexplorer and https://github.com/niklasf/tbserve in online anticrux.

**Comment by ecrucru** [comment]
Hello,

For sure, the endgame databases will not be implemented. The dynamic of the variant is not suitable for such an effort of development.

For the opening, yes, the feature is planned for a next release and it is very probable that the opening book will be offline. This is an identified domain where the AI can play better.

News to come in the future.

**Comment by ecrucru** [comment]
The feature is now available.
