### ISSUE TITLE
Using anticrux engine with PyChess GUI

### ISSUE THREAD

**Issue by gbtami** [ecrucru/anticrux#14]
Just a little nitpicking. Now https://github.com/ecrucru/anticrux#procedure-for-pychess say "To start a new game, you should always use the menu "File > New game" because the home screen is unable (at the current time) to start a variant game."

You can start the same dialog as "File > New game" from home screen just clicking on big weather icon button.

**Comment by ecrucru** [comment]
That's a good remark. The procedure is updated.

Thanks.
