### ISSUE TITLE
CinnamonJS running with JavaScript 1.2 on Arena

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#6]
Hello ecrucru,
cf. my threads on CCC here:
http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=727784&t=64908
http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=727787&t=64908

Has CinnamonJS a bug too that it cannot run on Arena www.playwitharena.com ?

**Comment by gbtami** [comment]
@yellow-panther cinnamon engine has it's own issue tracker at https://github.com/gekomad/Cinnamon/issues FYI

**Comment by ecrucru** [comment]
Hello @yellow-panther,

I am not able to provide any precise support for the other engines. Also, I have uninstalled Arena.

In echo to a previous reply in #4, please retry with NodeJS instead of jsUCI. It may explain why it forfeits on time.

Regards.
