### ISSUE TITLE
Anticrux 0.3.0 Javascript UCI vs. Sjeng 11.2 WB Suicide Chess

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#7]
Salut ecrucru,
ton logiciel fonctionne maintenant avec **Node.js 6.11.2 LTS 64** bit https://nodejs.org/en/ ( .exe)
et anticrux-engine.js (paramètre dans la ligne de commande)
contre **Sjeng 11.2 WB** https://sjeng.org/download.html existe une terrible défaite - 0:10

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "1"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "Sjeng 11.2"]
[Result "0-1"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. -0.70 1... -0.12"]

1. e3 {-0.70/4} e6 {-0.12/11 40} 2. b4 {-1.30/7 0.9} Bxb4 3. Bb2
{-1.30/5 0.8} Bxd2 4. Bxg7 {-0.70/8 0.3} Bxe3 5. Qxd7 {-0.90/8 1.3} Nxd7 6.
Bxh8 {-0.70/6 0.8} Bxf2 7. Kxf2 {+0.00/1 0.1} Ne5 8. Bxe5 {+0.80/1 0.1} Qd1
9. Bxc7 {+0.50/1 0.2} Qxb1 10. Rxb1 {+2.00/1 0.1} Bd7 11. Rxb7
{+2.70/1 0.1} Ba4 12. Rxa7 {+2.30/1 0.1} Bxc2 13. Rxa8 {+4.50/1 0.1} f6 14.
Rxe8 {+5.40/1 0.1} Nh6 15. Rxe6 {+6.10/1 0.2} Bb1 16. Rxf6 {+6.10/1 0.1}
Bxa2 17. Rxh6 {+7.70/1 0.1} Bb3 18. Rxh7 {+8.50/1 0.1} Bc4 19. Bxc4
{+1000.01/1 0.1}
{Xboard adjudication: Stalemate} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "2"]
[White "Sjeng 11.2"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. +0.32 1... +1.10"]

1. e3 {+0.32/9} b5 {+1.10/3 0.7} 2. Bxb5 Bb7 {+1.40/5 0.8} 3. Bxd7 Bxg2
{+1.10/6 1.2} 4. Bxe8 Qxd2 {+1.90/8 0.4} 5. Bxd2 {+6.37/11 24} Bxh1
{+1.10/1 0.1} 6. Bxf7 Bd5 {+3.10/6 0.8} 7. Bxg8 Bxa2 {+2.30/6 1.1} 8. Rxa2
Rxg8 {+2.10/1 0.1} 9. Rxa7 Rxa7 {+1.00/1 0.1} 10. Ba5 Rxa5 {-0.30/1 0.1}
11. Qd5 Rxd5 {-2.10/1 0.1} 12. Kd1 Rxd1 {-3.20/1 0.1} 13. Na3 Rxg1
{-4.40/1 0.1} 14. Nb1 Rxb1 {-5.60/1 0.1} 15. b4 Rxb4 {-6.50/1 0.1} 16. c4
Rxc4 {-7.40/1 0.1} 17. h4 Rxh4 {-8.20/1 0.1} 18. e4 Rxe4 {-9.10/1 0.1} 19.
f4 Rxf4 {-1000.01/1 0.1}
{Xboard adjudication: Stalemate} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "3"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "Sjeng 11.2"]
[Result "0-1"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. -0.70 1... -0.12"]

1. e3 {-0.70/4} e6 {-0.12/11 40} 2. Ba6 {-1.30/7 0.9} Nxa6 {+0.26/10 14} 3.
b4 {-1.60/6 0.8} Bxb4 4. Qf3 {-2.00/5 0.8} Bxd2 5. Qxb7 {-2.60/6 1.1} Bxe1
6. Qxa6 {-3.30/7 0.6} Bxf2 7. Qxa7 {-2.30/8 0.3} Bxe3 {+2.24/10 8} 8. Qxa8
{-2.80/7 0.7} Bxg1 {+2.58/11 10} 9. Qxc8 {-2.60/8 0.8} Qxc8 10. Rxg1
{-0.90/1 0.1} g5 11. Bxg5 {-0.30/1 0.1} Nf6 12. Bxf6 {+0.90/1 0.2} c6 13.
Bxh8 {+2.70/1 0.1} f6 14. Bxf6 {+3.60/1 0.1} e5 15. Bxe5 {+4.50/1 0.1} d6
16. Bxd6 {+5.40/1 0.1} Qh3 17. gxh3 {+7.10/1 0.2} c5 18. Bxc5 {+8.00/1 0.1}
Kf8 19. Bxf8 {+9.10/1 0.1} h6 20. Bxh6 {+1000.01/1 0.1}
{Xboard adjudication: Stalemate} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "4"]
[White "Sjeng 11.2"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. +0.32 1... +1.10"]

1. e3 {+0.32/9} b5 {+1.10/3 0.7} 2. Bxb5 Bb7 {+1.40/5 0.8} 3. Bxd7 Bxg2
{+1.10/6 1.3} 4. Bxe8 Qxd2 {+1.90/8 0.4} 5. Bxd2 {+6.37/11 24} Bxh1
{+1.10/1 0.1} 6. Bxf7 Bd5 {+3.10/6 0.8} 7. Bxg8 Bxa2 {+2.10/6 1.0} 8. Rxa2
Rxg8 {+2.10/1 0.1} 9. Rxa7 Rxa7 {+1.00/1 0.1} 10. Ba5 Rxa5 {-0.30/1 0.2}
11. Qd5 Rxd5 {-2.10/1 0.1} 12. Kd1 Rxd1 {-3.20/1 0.1} 13. Na3 Rxg1
{-4.40/1 0.1} 14. Nb1 Rxb1 {-5.60/1 0.2} 15. b4 Rxb4 {-6.50/1 0.1} 16. c4
Rxc4 {-7.40/1 0.1} 17. h4 Rxh4 {-8.20/1 0.1} 18. e4 Rxe4 {-9.10/1 0.1} 19.
f4 Rxf4 {-1000.01/1 0.1}
{Xboard adjudication: Stalemate} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "5"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "Sjeng 11.2"]
[Result "0-1"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. -0.70 1... -0.12"]

1. e3 {-0.70/4} e6 {-0.12/11 40} 2. b4 {-1.30/7 0.9} Bxb4 3. Bb2
{-1.30/5 0.7} Bxd2 4. Bxg7 {-0.70/8 0.3} Bxe3 5. Bxh8 {-0.90/8 1.4} Bxf2 6.
Qxd7 {-1.80/8 1.1} Nxd7 7. Kxf2 {+0.00/1 0.1} Ne5 8. Bxe5 {+0.80/1 0.1} Qd1
9. Bxc7 {+0.50/1 0.1} Qxb1 10. Rxb1 {+2.00/1 0.1} Bd7 11. Rxb7
{+2.70/1 0.1} Ba4 12. Rxa7 {+2.30/1 0.1} Bxc2 13. Rxa8 {+4.50/1 0.1} f6 14.
Rxe8 {+5.40/1 0.1} Nh6 15. Rxe6 {+6.10/1 0.1} Bb1 16. Rxf6 {+6.10/1 0.1}
Bxa2 17. Rxh6 {+7.70/1 0.1} Bb3 18. Rxh7 {+8.50/1 0.1} Bc4 19. Bxc4
{+1000.01/1 0.1}
{Xboard adjudication: Stalemate} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "6"]
[White "Sjeng 11.2"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. +0.32 1... +1.10"]

1. e3 {+0.32/9} b5 {+1.10/3 0.7} 2. Bxb5 Bb7 {+1.40/5 0.7} 3. Bxd7 Bxg2
{+0.90/6 1.2} 4. Bxe8 Qxd2 {+1.90/8 0.4} 5. Bxd2 {+6.37/11 24} Bxh1
{+1.10/1 0.1} 6. Bxf7 Bd5 {+3.10/6 0.8} 7. Bxg8 Bxa2 {+2.30/6 1.0} 8. Rxa2
Rxg8 {+2.10/1 0.1} 9. Rxa7 Rxa7 {+1.00/1 0.1} 10. Ba5 Rxa5 {-0.30/1 0.2}
11. Qd5 Rxd5 {-2.10/1 0.2} 12. Kd1 Rxd1 {-3.20/1 0.1} 13. Na3 Rxg1
{-4.40/1 0.1} 14. Nb1 Rxb1 {-5.60/1 0.2} 15. b4 Rxb4 {-6.50/1 0.1} 16. c4
Rxc4 {-7.40/1 0.1} 17. h4 Rxh4 {-8.20/1 0.1} 18. e4 Rxe4 {-9.10/1 0.1} 19.
f4 Rxf4 {-1000.01/1 0.1}
{Xboard adjudication: Stalemate} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "7"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "Sjeng 11.2"]
[Result "0-1"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. -0.70 1... -0.12"]

1. e3 {-0.70/4} e6 {-0.12/11 40} 2. Ba6 {-1.30/7 0.9} Nxa6 {+0.26/10 14} 3.
b4 {-1.60/6 0.9} Bxb4 4. Qf3 {-2.00/5 0.7} Bxd2 5. Qxb7 {-2.60/6 1.0} Bxe1
6. Qxa7 {-3.00/7 0.6} Bxf2 7. Qxa8 {-2.30/8 0.7} Bxg1 {+2.61/12 10} 8. Qxa6
{-2.50/6 0.8} Bxa6 9. Rxg1 {-1.30/1 0.2} Bf1 10. Rxf1 {-0.20/1 0.1} Qe7 11.
Rxf7 {-1.10/1 0.1} Qxf7 12. Nc3 {-2.10/4 1.0} Qf4 13. exf4 {+0.50/1 0.1} e5
14. fxe5 {+1.50/1 0.1} g5 15. Bxg5 {+2.50/1 0.1} Kd8 16. Bxd8 {+3.70/1 0.1}
Ne7 17. Bxe7 {+3.30/6 0.7} c5 18. Bxc5 {+6.00/1 0.1} Rf8 19. Bxf8
{+8.00/1 0.1} h6 20. Bxh6 {+9.00/1 0.1} d6 21. exd6 {+1000.01/1 0.1}
{Xboard adjudication: Stalemate} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "8"]
[White "Sjeng 11.2"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. +0.32 1... +1.10"]

1. e3 {+0.32/9} b5 {+1.10/3 0.7} 2. Bxb5 Bb7 {+1.40/5 0.8} 3. Bxd7 Bxg2
{+0.90/6 1.1} 4. Bxe8 Qxd2 {+1.90/8 0.5} 5. Bxd2 {+6.37/11 24} Bxh1
{+1.10/1 0.1} 6. Bxf7 Bd5 {+3.10/6 0.7} 7. Bxg8 Bxa2 {+2.40/6 1.0} 8. Rxa2
Rxg8 {+2.10/1 0.1} 9. Rxa7 Rxa7 {+1.00/1 0.1} 10. Ba5 Rxa5 {-0.30/1 0.1}
11. Qd5 Rxd5 {-2.10/1 0.1} 12. Kd1 Rxd1 {-3.20/1 0.1} 13. Na3 Rxg1
{-4.40/1 0.2} 14. Nb1 Rxb1 {-5.60/1 0.1} 15. b4 Rxb4 {-6.50/1 0.1} 16. c4
Rxc4 {-7.40/1 0.1} 17. h4 Rxh4 {-8.20/1 0.1} 18. e4 Rxe4 {-9.10/1 0.1} 19.
f4 Rxf4 {-1000.01/1 0.1}
{Xboard adjudication: Stalemate} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "9"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "Sjeng 11.2"]
[Result "0-1"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. -0.70 1... -0.12"]

1. e3 {-0.70/4} e6 {-0.12/11 40} 2. b4 {-1.30/7 0.9} Bxb4 3. Bb2
{-1.30/5 0.7} Bxd2 4. Bxg7 {-0.70/8 0.3} Bxe3 5. Qxd7 {-0.90/8 1.3} Nxd7 6.
Bxh8 {-0.70/6 0.8} Bxf2 7. Kxf2 {+0.00/1 0.1} Ne5 8. Bxe5 {+0.80/1 0.1} Qd1
9. Bxc7 {+0.50/1 0.1} Qxb1 10. Rxb1 {+2.00/1 0.1} Bd7 11. Rxb7
{+2.70/1 0.1} Ba4 12. Rxa7 {+2.30/1 0.2} Bxc2 13. Rxa8 {+4.50/1 0.1} f6 14.
Rxe8 {+5.40/1 0.1} Nh6 15. Rxe6 {+6.10/1 0.1} Bb1 16. Rxf6 {+6.10/1 0.1}
Bxa2 17. Rxh6 {+7.70/1 0.1} Bb3 18. Rxh7 {+8.50/1 0.1} Bc4 19. Bxc4
{+1000.01/1 0.1}
{Xboard adjudication: Stalemate} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "10"]
[White "Sjeng 11.2"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Variant "suicide"]
[Annotator "1. +0.32 1... +1.10"]

1. e3 {+0.32/9} b5 {+1.10/3 0.7} 2. Bxb5 Na6 {+0.80/5 0.8} 3. Bxa6 Bxa6
{+0.20/1 0.1} 4. c4 Bxc4 {-0.30/1 0.1} 5. Qg4 Bxa2 {-0.10/1 0.1} 6. Qxg7
Bxg7 {+0.20/7 0.7} 7. Rxa2 Bxb2 {-0.10/1 0.1} 8. Rxb2 Rc8 {+1.20/3 0.7} 9.
Rb8 Rxb8 {-1.30/1 0.1} 10. Kd1 Rxb1 {-2.20/1 0.1} 11. Ke2 Rxc1
{-3.40/1 0.1} 12. Nf3 Rxh1 {-4.90/1 0.2} 13. Nd4 Rxh2 {-5.50/1 0.2} 14. d3
Rxg2 {-6.20/1 0.1} 15. Kd1 Rxf2 {-6.90/1 0.1} 16. Kd2 Rxd2 {-7.70/1 0.1}
17. Nb3 Rxd3 {-8.40/1 0.2} 18. Na1 Rxe3 {-9.10/1 0.1} 19. Nb3 Rxb3
{-1000.01/1 0.1}
{Xboard adjudication: Stalemate} 1-0

**Comment by ecrucru** [comment]
Hello,

This output is absolutely not a surprise since AntiCrux is not designed to be unbeatable, on the contrary. This is something I used to mention in the 2nd paragraph of the presentation :
https://github.com/ecrucru/anticrux/blob/master/README.md#presentation

Also, you don't specify which level you have defined. By default, AntiCrux runs at level 9 which is 70k nodes. You can at least boost to the level 18 (750k nodes) but it will not change the ELO so much in practice. When I see the 8th move of the 10th game, it is clear that the level has not been changed for this mini competition.
https://github.com/ecrucru/anticrux/blob/master/README.md#levels

I am satisfied that you was able to run the games. I verified the played moves and I see nothing wrong with them.

Regards.

**Comment by yellow-panther** [comment]
I used the default settings of Sjeng and other Suicide Chess engines - on https://github.com/ecrucru/anticrux/releases version 0.3.0 is not mentioned > accidentally or intentionally, that's not clear for me

regards

**Comment by ecrucru** [comment]
Hello,

The version 0.3.0 is not released but the current master is not so far from it. My todo list still has some interesting features to be implemented and few bugs to be analyzed.

Whatever the level (set [here](https://github.com/ecrucru/anticrux/blob/master/anticrux.js#L2403) by default), the point is that my little engine doesn't go upper than 1750 ELO according to some statistical measures I have done against [Stockfish with multi-variant support](https://github.com/ddugovic/Stockfish). Consequently, competing against Sjeng or Pulsar is lost in advance since these engines rely on enhanced techniques.

Regards
