### ISSUE TITLE
Anticrux UCI JavaScript Chess vs. Pulsar 2009-9b

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#8]
http://www.lanternchess.com/pulsar/ - encore 0:10

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "1"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "pulsar2009-9b"]
[Result "0-1"]
[TimeControl "300"]
[Annotator "1. -0.70   1... +0.05"]

1. e3 {-0.70/4} e5 {+0.05/8 10} 2. Ba6 {-1.40/7 1.0} Nxa6 {+3.39/8 14} 3.
b4 {-2.30/7 1.3} Nxb4 {+4.31/8 11} 4. Qh5 {-3.00/7 1.1} Nxc2+ {+7.05/8 13}
{Xboard: Forfeit due to invalid move: h5e5 (h5e5 via `0, `0) res=24} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "2"]
[White "pulsar2009-9b"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Annotator "1. +0.35   1... +1.40"]

1. e4 {+0.35/8} b5 {+1.40/6 1.0} 2. Bxb5 {+1.40/8 12} f5 {+1.60/6 1.3} 3.
exf5 {+2.78/8 10} Nh6 {+2.00/6 1.1} 4. Qh5+ {+3.14/8 10}
{False draw claim: 'stalemate'} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "3"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "pulsar2009-9b"]
[Result "0-1"]
[TimeControl "300"]
[Annotator "1. -0.70   1... +0.05"]

1. e3 {-0.70/4} e5 {+0.05/8 11} 2. Ba6 {-1.40/7 1.0} Nxa6 {+3.39/8 12} 3.
b4 {-1.60/7 1.3} Nxb4 {+4.31/8 11} 4. Qe2 {-2.80/7 1.2} Nxc2+ {+8.97/8 11}
5. Kd1 {-3.40/6 0.9} Nxa1 {+9.38/8 9} 6. Qa6 {-4.20/6 1.2} bxa6
{+20.49/8 9}
{Xboard: Forfeit due to invalid move: d1c2 (d1c2 via `0, `0) res=24} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "4"]
[White "pulsar2009-9b"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Annotator "1. +0.35   1... +1.60"]

1. e4 {+0.35/8} f5 {+1.60/6 1.1} 2. exf5 {+1.41/8 12} b5 {+1.60/5 0.9} 3.
Qh5+ {+7.33/8 13}
{False draw claim: 'stalemate'} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "5"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "pulsar2009-9b"]
[Result "0-1"]
[TimeControl "300"]
[Annotator "1. -0.70   1... +0.05"]

1. e3 {-0.70/4} e5 {+0.05/8 14} 2. Ba6 {-2.00/7 1.1} Nxa6 {+3.39/8 13} 3.
h4 {-1.60/7 1.2} d5 {+3.45/8 12}
{False draw claim: 'stalemate'} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "6"]
[White "pulsar2009-9b"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Annotator "1. +0.35   1... +1.60"]

1. e4 {+0.35/8} f5 {+1.60/6 1.0} 2. exf5 {+1.41/8 12} b5 {+1.60/5 1.0} 3.
Qh5+ {+7.33/8 10}
{False draw claim: 'stalemate'} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "7"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "pulsar2009-9b"]
[Result "0-1"]
[TimeControl "300"]
[Annotator "1. -0.70   1... +0.05"]

1. e3 {-0.70/4} e5 {+0.05/8 12} 2. Ba6 {-1.40/7 1.0} Nxa6 {+3.39/8 12} 3.
b4 {-2.30/7 1.2} Nxb4 {+4.45/8 12} 4. Qg4 {-2.80/7 1.2} Nxc2+ {+8.73/8 11}
{Xboard: Forfeit due to invalid move: g4g7 (g4g7 via `0, `0) res=24} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "8"]
[White "pulsar2009-9b"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Annotator "1. +0.35   1... +1.60"]

1. e4 {+0.35/8} f5 {+1.60/6 1.1} 2. exf5 {+1.41/8 14} Nf6 {+1.00/5 1.0} 3.
Bd3 {+1.50/8 9} Ne4 {+2.00/4 0.9} 4. Qh5+ {+8.11/8 13}
{False draw claim: 'stalemate'} 1-0

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "9"]
[White "AntiCrux 0.3.0 (UCI2WB)"]
[Black "pulsar2009-9b"]
[Result "0-1"]
[TimeControl "300"]
[Annotator "1. -0.70   1... +0.05"]

1. e3 {-0.70/4} e5 {+0.05/8 13} 2. Ba6 {-2.00/7 1.1} Nxa6 {+3.39/8 13} 3.
h4 {-1.60/7 1.2} d5 {+3.45/8 10}
{False draw claim: 'stalemate'} 0-1

[Event "Computer Chess Game"]
[Site "QUADCORE-I5"]
[Date "2017.08.16"]
[Round "10"]
[White "pulsar2009-9b"]
[Black "AntiCrux 0.3.0 (UCI2WB)"]
[Result "1-0"]
[TimeControl "300"]
[Annotator "1. +0.35   1... +1.40"]

1. e4 {+0.35/8} b5 {+1.40/6 1.0} 2. Bxb5 {+1.40/8 14} f5 {+1.60/6 1.3} 3.
exf5 {+2.78/8 10} Nh6 {+2.00/6 1.0} 4. Qh5+ {+3.14/8 12}
{False draw claim: 'stalemate'} 1-0

**Comment by ecrucru** [comment]
Hello @yellow-panther,

Obviously, these games are not suicide games. The explanation will be the same as #7.

Regards
