### ISSUE TITLE
Scidb (Linux) and implementation of JavaScript engines

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#9]
Hello ecrucru,
**Gregor** http://www.talkchess.com/forum/profile.php?mode=viewprofile&u=7105 told me in German:
**Scidb** http://scidb.sourceforge.net/ - die Unterstützung von Javascript-Motoren ist noch nicht realisiert, und hat zur Zeit keine Priorität, (Scidb does not support JavaScript engines - realization has a low priority at the moment)
please take a look at the following features for Suicide Chess:
**Endgame Tablebases** https://catalin.francu.com/nilatac/ (4 pieces)
**FICS Games DataBase** http://ficsgames.org/
**Suicide Chess Server** https://catalin.francu.com/colibri/www/

**Comment by ecrucru** [comment]
Hello,

**1)** No issue -- It is up to SciDb to decide of its priorities. Such a feature was kindly added into pyChess 5 months ago, so there is no reason that SciDb won't be able to achieve the same nice result.

**2)** Unexpectable enhancement -- The enggame databases are huge by definition. The use of external data providers is not considered. I know that AntiCrux is not always able to finish a game properly but it depends on the remaining pieces and the selected level.

**3)** No issue -- The FICS games database is a compilation of all the games played on FICS. There is nothing related with the current project.

**4)** No issue -- Colibri is the new Nilatac. If you can get it as an UCI-compatible engine, then you will be able to run computer matchs. The output is predictable when you see how fast its web user interface is.

Regards.
